schemaVersion: 2.2.0
metadata:
  name: msip-workspace
  version: 1.0.0
  displayName: MSIP Development Environment
  description: Workspace para desarrollo de MSIP (Ruby on Rails)
  language: Ruby
  projectType: Rails

components:
  - name: tooling-container
    container:
      image: registry.gitlab.com/gitlab-org/gitlab-development-kit/gitpod-workspace:stable
      memoryLimit: 4Gi
      memoryRequest: 2Gi
      cpuLimit: 2000m
      cpuRequest: 1000m
      mountSources: true
      env:
        - name: RAILS_ENV
          value: development
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@localhost:5432/msip_development
      endpoints:
        - name: rails-server
          targetPort: 3000
          exposure: public
          protocol: http
        - name: webpack-dev-server
          targetPort: 3035
          exposure: public
          protocol: http

  - name: postgresql
    container:
      image: postgres:14
      memoryLimit: 1Gi
      memoryRequest: 512Mi
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: msip_development
      endpoints:
        - name: postgresql
          targetPort: 5432
          exposure: internal
      volumeMounts:
        - name: postgresql-data
          path: /var/lib/postgresql/data

  - name: postgresql-data
    volume:
      size: 2Gi

commands:
  - id: install-dependencies
    exec:
      label: "Instalar dependencias"
      component: tooling-container
      workingDir: ${PROJECT_SOURCE}
      commandLine: |
        bundle install
        yarn install || npm install
      group:
        kind: build
        isDefault: true

  - id: setup-database
    exec:
      label: "Configurar base de datos"
      component: tooling-container
      workingDir: ${PROJECT_SOURCE}
      commandLine: |
        bundle exec rake db:create db:migrate db:seed
      group:
        kind: build

  - id: run-tests
    exec:
      label: "Ejecutar tests"
      component: tooling-container
      workingDir: ${PROJECT_SOURCE}
      commandLine: |
        bundle exec rake test
      group:
        kind: test

  - id: start-rails-server
    exec:
      label: "Iniciar servidor Rails"
      component: tooling-container
      workingDir: ${PROJECT_SOURCE}
      commandLine: |
        bundle exec rails server -b 0.0.0.0
      group:
        kind: run
        isDefault: true

  - id: rails-console
    exec:
      label: "Abrir consola Rails"
      component: tooling-container
      workingDir: ${PROJECT_SOURCE}
      commandLine: |
        bundle exec rails console
      group:
        kind: run

events:
  postStart:
    - install-dependencies
