# Este flujo de trabajo emplea acciones que no están certificadas por Github.
# Son proveidas por un tercero y están gobernadas por diferentes
# términos de servicio, política de privacidad y documentación.
#
# Este flujo de trabajo instalará una versión preconstruida de Ruby,
# instalará dependencias y ejecutará pruebas y verificadores.
name: "IC para Ruby on Rails"
on:
  push:
    branches: [ "main", "v2.2" ]
  pull_request:
    branches: [ "main", "v2.2" ]
env:
  DB_HOST: localhost
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:16-3.4
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
          BD_CLAVE: password
          BD_USUARIO: rails
          BD_PRUEBA: rails_test
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Sacar código fuente
        uses: actions/checkout@v3
      # Agregue o remplace pasos de depencicas aquí
      - name: Instalar Ruby y gemas
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'
          bundler-cache: true
      - name: Instalar paquetes adicionales
        run: (sudo locale-gen es_CO.UTF-8; cat /etc/locale-alias;  echo "es_CO.UTF-8 es_CO.utf8" | sudo tee -a /etc/locale.alias; sudo update-locale; sudo locale -a; sudo apt install poppler-utils postgis postgresql-16-postgis; sudo service postgresql restart)
      - name: Modificar volcados para que operen en versiones antiguas de PostgreSQL
        run: (cp test/dummy/db/structure.sql test/dummy/db/structure.sql.copia; sed -e 's/provider = libc,//g;s/SET default_table_access_method.*/-- &/g;s/SET transaction_timeout.*//g' test/dummy/db/structure.sql.copia > test/dummy/db/structure.sql; cp db/datos-basicas.sql db/datos-basicas.sql.copia; sed -e 's/provider = libc,//g;s/SET default_table_access_method.*/-- &/g;s/SET transaction_timeout.*//g' db/datos-basicas.sql.copia > db/datos-basicas.sql)
      - name: Configurar esquema de base de datos
        run: (cd test/dummy; cp .env.github .env; RAILS_ENV=test bin/rails db:drop db:create db:setup db:seed msip:indices; bin/rails msip:stimulus_motores; bin/rails assets:precompile)
      # Agregue o remplace ejecutores de pruebas aquí
      - name: Ejecutar pruebas
        run: CONFIG_HOSTS=www.example.com RUTA_RELATIVA=/ bin/rails tes

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Sacar código fuente
        uses: actions/checkout@v3
      - name: Instalar Ruby y gemas
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'
          bundler-cache: true
      # Agregue o remplace verificadores 
      - name: Verificación de seguridad a dependencias ruby
        run: (bin/bundler-audit --update || exit_code=$?; echo "exit_code=$exit_code")
      - name: Verificación de seguridad a código Ruby de la aplicación
        run: (bin/brakeman -q -w2 || exit_code=$?; echo "exit_code=$exit_code")
      - name: Verificación al formato de código Ruby
        run: (bin/rubocop --parallel || exit_code=$?; echo "exit_code=$exit_code")
